[[headers]]
  for = "/images/*" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.webp" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"


[[headers]]
  for = "/*.png" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.jpg" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"


[[headers]]
  for = "/*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"